import Head from 'next/head'
import React, { useState, useEffect, useMemo } from "react";
import useSWRInfinite from "swr/infinite";
import styles from '../styles/Home.module.css'
import Placeholder from '../components/Placeholder';
import Post from '../components/Post';

const fetcher = url => fetch(url).then(res => res.json());
const PAGE_SIZE = 10;


export default function Home() {

  const { data, error, mutate, size, setSize, isValidating } = useSWRInfinite(
    index =>
      `https://ronan-oleary.com/wp-json/wp/v2/posts?page=${index +
        1}`,
    fetcher,
  );

  
  const posts = data ? [].concat(...data) : [];
  const isLoadingInitialData = !data && !error;
  const isLoadingMore = isLoadingInitialData || (size > 0 && data && typeof data[size - 1] === "undefined");
  const isEmpty = data?.[0]?.length === 0;
  const isReachingEnd = isEmpty || (data && data[data.length - 1]?.length < PAGE_SIZE);
  const isRefreshing = isValidating && data && data.length === size
  

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Client Test: POC#1
        </h1>

        <Placeholder text={'Oh what a world'} />
        {isLoadingInitialData ? <svg
        id="loading-spinner"
        xmlns="http://www.w3.org/2000/svg"
        width="48"
        height="48"
        viewBox="0 0 48 48"
        style={{ margin: '2rem auto' }}
      >
        <g fill="none">
          <path
            id="track"
            fill="#C6CCD2"
            d="M24,48 C10.745166,48 0,37.254834 0,24 C0,10.745166 10.745166,0 24,0 C37.254834,0 48,10.745166 48,24 C48,37.254834 37.254834,48 24,48 Z M24,44 C35.045695,44 44,35.045695 44,24 C44,12.954305 35.045695,4 24,4 C12.954305,4 4,12.954305 4,24 C4,35.045695 12.954305,44 24,44 Z"
          />
          <path
            id="section"
            fill="#3F4850"
            d="M24,0 C37.254834,0 48,10.745166 48,24 L44,24 C44,12.954305 35.045695,4 24,4 L24,0 Z"
          />
        </g>
      </svg> : 
        <ul>
            {posts.map((post, idx) => (
              <Post post={post} key={idx} />
            ))}


        </ul>
        }
        <br />
        <button
          className={`bg-black hover:bg-gray-700 text-white font-bold py-2 px-4 rounded`}
          disabled={isLoadingMore || isReachingEnd}
          onClick={() => setSize(size + 1)}>
          {isLoadingMore
              ? 'Loading...'
              : isReachingEnd
                  ? 'No More Posts'
                  : 'Load More'}
      </button>
      </main>
    </div>
  )
}
